reworked configure-maxscale-repo, cleaned up some other scripts

diff --git a/setup-maxscale-repos.sh.in b/setup-maxscale-repos.sh.in
--- a/setup-maxscale-repos.sh.in
+++ b/setup-maxscale-repos.sh.in
@@ -1,69 +1,70 @@
 #!/bin/bash
 
-path_to_repo=$1
+default_path_to_repo="@REPO_URL@"
+path_to_repo="${1:-$default_path_to_repo}"
 
-if [[ -z "$path_to_repo" ]]; then
-	path_to_repo="http://@REPO_URL@"
-fi 
-
-distro_name="centos"
 maxdir="@CMAKE_INSTALL_PREFIX@"
 
-zypper --version 2> /dev/null > /dev/null
-if [[ $? == 0 ]]; then
+if command -v zypper &>/dev/null; then
 	# it is SUSE
-	release_info=$(cat /etc/*-release 2>/dev/null)
-	if [[ $(echo "$release_info" | grep 'VERSION = 13') != "" ]]; then
+	#/etc/SuSE-release is deprecated, so we prefer /etc/os-release
+	if [[ -e /etc/os-release ]] ; then
+		IFS=. read -r distro_version minor < <(
+			awk -F' *= *' '$1=="VERSION_ID"{gsub(/"/,"",$2); print $2 }' /etc/os-release
+		)
+	else
+		#SLES 11 doesn't have /etc/os-release
+		distro_version=$(awk -F' *= *' '$1=="VERSION"{print $2}' /etc/SuSE-release)
+	fi
+
+	if [[ ! $distro_version ]]; then
+		echo "[ERROR] couldn't determine OS version. Aborting." >&2
+		exit 1
+	fi
+
+	# this distro_name variable is not actually used right now?
+	if ((distro_version==13)); then
 		# we have opensuse only for version 13 (should be fixed later)
                 distro_name="opensuse"
-		sed "s|####path_to_repo####|$path_to_repo|g" $maxdir/maxscale.repo.suse13.template > /etc/zypp/repos.d/maxscale.repo
 	else
                 distro_name="sles"
-		if [[ $(echo "$release_info" | grep 'VERSION = 12') != "" ]]; then
-			sed "s|####path_to_repo####|$path_to_repo|g" $maxdir/maxscale.repo.sles12.template > /etc/zypp/repos.d/maxscale.repo
-		else
-			sed "s|####path_to_repo####|$path_to_repo|g" $maxdir/maxscale.repo.sles11.template > /etc/zypp/repos.d/maxscale.repo
-		fi
         fi
-	#rpm --import $path_to_repo/Maxscale-GPG-KEY.public
-else
-	yum --version 2> /dev/null > /dev/null
-	if [[ $? == 0 ]]; then
-		# there is YUM here
-		release_info=$(cat /etc/*-release 2>/dev/null)
-		if [[ $(echo "$release_info" | grep 'ID=' | grep 'rhel') != "" ]]; then
-			distro_name="rhel"
-		fi
-		if [[ $(echo "$release_info" | grep 'ID=' | grep 'fedora') != "" ]]; then
-        		distro_name="fedora"
-		fi
 
-		sed "s|####path_to_repo####|$path_to_repo|g" $maxdir/maxscale.repo.template | sed "s|####distro_name####|$distro_name|g"> /etc/yum.repos.d/maxscale.repo
+	sed "s|####path_to_repo####|$path_to_repo|g" \
+	    "$maxdir/maxscale.repo.suse$distro_version.template" \
+	    > /etc/zypp/repos.d/maxscale.repo
+	#rpm --import "$path_to_repo/Maxscale-GPG-KEY.public"
+
+elif command -v yum &>/dev/null; then
+	# there is yum here
+	distro_name="rhel" #rhel covers RHEL and CentOS
+	if [[ -e /etc/os-release ]] && grep -q '^ID=.*fedora' /etc/os-release; then
+		distro_name="fedora"
 	fi
-fi
 
-apt-get --version 2> /dev/null > /dev/null
-if [[ $? == 0 ]]; then
+	sed -e "s|####path_to_repo####|$path_to_repo|g" \
+	    -e  "s|####distro_name####|$distro_name|g" \
+	    "$maxdir"/maxscale.repo.template \
+	    > /etc/yum.repos.d/maxscale.repo
+
+elif command -v apt-get &>/dev/null ; then
 	# there is apt-get here
-	release_info=$(cat /etc/*-release 2>/dev/null)
-	if [[ $(echo "$release_info" | grep 'Ubuntu') != "" ]]; then
+	if [[ $(lsb_release -sd) = Ubuntu* ]]; then 
 		distro_name="ubuntu"
-		distro_codename=$(cat /etc/*-release 2>/dev/null | grep "DISTRIB_CODENAME" | sed "s/DISTRIB_CODENAME=//")
 	else 
         	distro_name="debian"
-                distro_version=$(release_info=$(cat /etc/debian_version); \
-                        [[ "$release_info" =~ [[:space:]]*([0-9]*\.[0-9]*) ]] && echo ${BASH_REMATCH[1]})
-                case "$distro_version" in
-                        "6"*) distro_codename="squeeze"
-                                ;;
-                        "7"*) distro_codename="wheezy"
-                                ;;
-#                        "8"*) distro_codename="sid"
-#                                ;;
-                esac
-
 	fi
+	distro_codename=$(lsb_release -sc)
 	
-	sed "s|####path_to_repo####|$path_to_repo|g" $maxdir/maxscale.list.template | sed "s|####distro_name####|$distro_name|g" |sed "s|####distro_codename####|$distro_codename|g" > /etc/apt/sources.list.d/maxscale.list
-	cat /etc/pki/rpm-gpg/Maxscale-GPG-KEY.public | apt-key add -
+	sed -e "s|####path_to_repo####|$path_to_repo|" \
+	    -e "s|####distro_name####|$distro_name|" \
+	    -e "s|####distro_codename####|$distro_codename|" \
+	    "$maxdir"/maxscale.list.template \
+	    > /etc/apt/sources.list.d/maxscale.list
+
+	apt-key add "$maxdir/Maxscale-GPG-KEY.public"
+else
+	# some unknown Linux, apparently...
+	echo "[ERROR] unable to identify operating system. Aborting. Please report this error.">&2 
+	exit 1
 fi
